### ISSUE TITLE
network.allneighbordistances documentation not accurate

### ISSUE THREAD

**Issue by jGaboardi** [pysal/spaghetti#111]
Currently,  the doctoring for `network.allneighbordistances` lists the `sourcepattern` and `destpattern` parameters as `str`s. However, the method actually takes a `network.PointPattern` for each of those.  Either (a) change the docstring to reflect the method; or (b) change the method to reflect the docstring.  `network.nearestneighbordistances` follows the same docstring format but the actual method corresponds with the docstring.

- [x] fix code

- [x] fix docstrings

- [x] fix examples

- [x] fix tests

- [x] fix notebooks

----------------------------------------

```python
Parameters
----------
sourcepattern : str
    The key of a point pattern snapped to the network.
destpattern : str
    (Optional) The key of a point pattern snapped to the network.
```

------------------------------------------

```python
        # Source setup
        src_indices = list(sourcepattern.points.keys())
        nsource_pts = len(src_indices)
        src_dist_to_node = sourcepattern.dist_to_node
        src_nodes = {}
        for s in src_indices:
            e1, e2 = src_dist_to_node[s].keys()
            src_nodes[s] = (e1, e2)
            
        # Destination setup
        symmetric = False
        if destpattern is None:
            symmetric = True
            destpattern = sourcepattern
        dest_indices = list(destpattern.points.keys())
```

**Comment by jGaboardi** [comment]
#112 allows to either pattern key (`str`) or the full `spaghetti.network.PointPattern object` to be passed in to `allneighbordistances` as the `sourcepattern` and `destpattern` parameters.

**Comment by MSOANCAH** [comment]
is network.allneighbourdistances giving correct result?? when i see the values in distance matrix given by qgis, the result given by network.allneighbourdistances  seems incorrect?? please help

**Comment by jGaboardi** [comment]
@MSOANCAH Thanks for the report! Please open a [new issue](https://github.com/pysal/spaghetti/issues/new/choose) for this if you believe that `spaghetti` is calculating distances incorrectly. Without clear and thorough documentation it will not be possible to troubleshoot any potential error, so please follow the template for issue reporting and provide source code and data for a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example).

**Comment by MSOANCAH** [comment]
@jGaboardi thanks for your reply..I will do that. But i have some doubt regarding the data preparation steps in facility location problem. I have seen your code, you have street network and then you are adding buffer to get area and then you are creating network. in my case i am not using road network, I am directly using a country shape file as i am working on facility location problem for whole country.
Is it correct or street network is required??.  can i get proper documentation how network is formed? and what is mean by snapobservation and pointpattern. Please help me with this. So that i can get clear idea till now i was just referring to your code.

**Comment by jGaboardi** [comment]
- If you are referring to the [`Optimal Facility Location: Integration with ortools`  notebook](https://nbviewer.jupyter.org/gist/jGaboardi/a671d31a796e06d9df669d018d5b66ba), that is simply a use case demonstration of four facility location problems constrained to a network with [google's `ortools`](https://developers.google.com/optimization/) and is not directly related to [`pysal/spaghetti`](https://github.com/pysal/spaghetti) itself.

- In terms of facility location model formulations, I will refer you to the **Scenario** cell in the notebook where four citations are listed. Two more great sources are:

   - **Daskin, Mark S**. 2013. Network and Discrete Location: Models, Algorithms and Applications. 2nd Edition. John Wiley & Sons, Inc. Hoboken, NJ.

  - **Church, Richard L. and Murray, Alan T.** 2009. Business Site Selection, Locational Analysis, and GIS. John Wiley & Sons, Inc. Hoboken, NJ.

- As for the `spaghetti` documentation, see the [API Reference](https://pysal-spaghetti.readthedocs.io/en/latest/api.html), specifically for [`spaghetti.Network.snapobservations`](https://pysal-spaghetti.readthedocs.io/en/latest/generated/spaghetti.Network.snapobservations.html#spaghetti.Network.snapobservations) and [`spaghetti.PointPattern`](https://pysal-spaghetti.readthedocs.io/en/latest/generated/spaghetti.PointPattern.html#spaghetti.PointPattern). The documentation in the API Reference is generated from `docstrings` found within the code itself, like the [`PointPattern` docstring](https://github.com/pysal/spaghetti/blob/348bba2835ef6a91e995cf011eba24ea832e44ed/spaghetti/network.py#L2370-L2429), for example. There you will also find `inline comments`, like this in [`snapobservations`](https://github.com/pysal/spaghetti/blob/348bba2835ef6a91e995cf011eba24ea832e44ed/spaghetti/network.py#L926-L927), for example.

**Comment by jGaboardi** [comment]
I will be locking this issue now, as it is not a bug report.
