### ISSUE TITLE
ImportError: No module named 'boto3'

### ISSUE THREAD

**Issue by jGaboardi** [pysal/spaghetti#113]
@ljwolf There is a fresh problem with `geopandas` dependency on `fiona` ([the issue is also referenced here](https://github.com/Toblerity/Fiona/issues/507)) in that [`boto3` is being imported](https://travis-ci.org/pysal/spaghetti/jobs/429211113#L929-L942), but not listed as a requirement for `geopandas`, which is causing `spaghetti` builds to fail. Would you recommend just waiting this out or is there something more concrete I could do?

**Comment by jGaboardi** [comment]
resolved

**Comment by ljwolf** [comment]
Weird bug. Good you sorted this.

**Comment by jGaboardi** [comment]
I did nothing LOL. @ocefpaf fixed it.

**Comment by ocefpaf** [comment]
Sorry for the headache. Due to an issue in conda-forge the `dev` version of `fiona` ended up in the `main` channel. I just moved it to the `dev` label and things should be OK now.

**Comment by jGaboardi** [comment]
@ocefpaf no problem! and thanks for all your work!
