### ISSUE TITLE
Project Description on PyPI

### ISSUE THREAD

**Issue by jGaboardi** [pysal/spaghetti#131]
The [Project description on PyPI](https://pypi.org/project/spaghetti/1.1.1/) is not rendering correctly. This is causing invalid/missing information in the badges on the `README` files.

@weikang9009 it seems like your package descriptions on pypi on rendering properly. Any thoughts on how I can fix this?

**Comment by weikang9009** [comment]
Try [this](https://github.com/pysal/giddy/blob/master/setup.py#L15): 
```python
DOCLINES = __doc__.split("\n")
```

and then in the [setup function](https://github.com/pysal/giddy/blob/master/setup.py#L58):
`description=DOCLINES[0],`

**Comment by weikang9009** [comment]
I think it makes more sense to define the [long_description](
 https://github.com/pysal/giddy/blob/master/setup.py#L60) by [reading the README](https://github.com/pysal/giddy/blob/master/setup.py#L17)

**Comment by jGaboardi** [comment]
@weikang9009 Ah. OK, I will try this again later. Thanks!
