### ISSUE TITLE
Deprecation: Container-Based Linux Build Environments

### ISSUE THREAD

**Issue by jGaboardi** [pysal/spaghetti#188]
@ljwolf I received this from Travis CI this morning (maybe everybody using TravisCI did?). I am not really clear about how/what should be changed (or if anything should be...). Any thoughts?

> Deprecation: Container-Based Linux Build Environments
> Hi jGaboardi! 
> 
> We’re emailing to make sure you know about the ongoing deprecation of the container-based Linux build environment. As we have communicated on the blog, and our changelog, we are now routing all Linux builds to the virtual-machine-based Linux infrastructure (“sudo: required” infrastructure). We believe this change facilitates a more intuitive build configuration experience that is more in line with how the majority of our customers and community use Travis CI. 
> 
> Starting today, we will begin routing all Linux builds to the virtual-machine-based infrastructure, regardless of the setting for the sudo keyword in a .travis.yml file. We expect minimal impact to your builds, unless you specifically safelist Travis CI IPs as part of your CI/CD pipeline. If so, we recommend you update those values (see the docs for the new IPs to use). The virtual-machine based environment has all the same tools as the container-based environment, along with better compute resources and support for building Docker containers. 
> 
> We’re contacting you directly as it looks like you have at least one repository that ran a build within the last week on your open- and/or closed-source projects, where the build configuration is explicitly configured for the container-based build environment. This build configuration(s) may potentially be affected by this change, so we wanted you to be aware this change is happening. Your build traffic will be migrated automatically soon, or your can opt-in sooner by changing your .travis.yml(s) to use sudo: required. 
> 
> Of course, if you have any questions at all, please feel free to contact us at support@travis-ci.com, or let us know on the community forum.
> 
> 
> Happy building!
> 
> Thanks so much,
> Travis CI Product Team

**Comment by jGaboardi** [comment]
This does not appear to be a issue for `spaghetti`. Closing for now.

**Comment by ljwolf** [comment]
Thanks dude. Iirc, we fixed this in 2014 in pysal, but it may still affect individual repositories? I got no note from Travis.

**Comment by jGaboardi** [comment]
The email would be significantly more helpful if it indicated WHICH repo... It doesn't seem the current build failures with `libpysal` are related to this. Might be a `GeoDa` issue though...
