### ISSUE TITLE
AttributeError: module 'spaghetti' has no attribute 'element_as_gdf'

### ISSUE THREAD

**Issue by wa-bhe** [pysal/spaghetti#242]
**Describe the bug**
`AttributeError: module 'spaghetti' has no attribute 'element_as_gdf'`

**To Reproduce**
Opening network.py in https://github.com/pysal/spaghetti/releases/tag/1.1.1.post3 you cannot find the `element_as_gdf` function.

**Expected behavior**
`network.py` in https://github.com/pysal/spaghetti/releases/tag/1.1.1.post3 should match https://pysal-spaghetti.readthedocs.io/en/latest/_modules/spaghetti/network.html#element_as_gdf

As this is an issue with the source code/release itself I will omit any specific details about the environment.

I wondered if the `element_as_gdf` and associated functions are just not released yet, but I can see the 1.1.1post3 documentation already has an entry for `element_as_gdf`. So there appears to be a mismatch between the docs and released code.

**Comment by jGaboardi** [comment]
@wa-bhe Thanks for the report (and reminding me about doing this). I had forgotten to cut a release with the new stuff in it. I will try to get that out today.

**Comment by jGaboardi** [comment]
@wa-bhe New releases are available on [PyPI](https://pypi.org/project/spaghetti/1.2/) and [GitHub](https://github.com/pysal/spaghetti/releases/tag/v1.2).
