### ISSUE TITLE
Prepare a release of spaghetti for pypi

### ISSUE THREAD

**Issue by sjsrey** [pysal/spaghetti#26]
At the moment, the [install instructions](https://github.com/pysal/spaghetti) will fail:

```
serge@yoga:~$ pip install spaghetti
Collecting spaghetti
  Could not find a version that satisfies the requirement spaghetti (from versions: )
No matching distribution found for spaghetti
```

**Comment by jGaboardi** [comment]
@sjsrey could you give me some direction on how to a release of spaghetti for pypi?

**Comment by jGaboardi** [comment]
@sjsrey @ljwolf `spaghetti v1.0.1` is now up on PyPI.
