### ISSUE TITLE
Solo owner/maintainer

### ISSUE THREAD

**Issue by jGaboardi** [pysal/spaghetti#270]
As per the discussion in pysal/pysal#1068 there are many `pysal` submodules that have only one maintainer/owner with admin/write privileges. This is the case with `pysal/spaghetti` for [`pypi`](https://pypi.org/manage/project/spaghetti/collaboration/) and [`readthedocs`](https://readthedocs.org/dashboard/pysal-spaghetti/users/).

 - `pypi`
   - one owner, multiple maintainer
   - [x] add an additional owner -- @knaaptime 

- `readthedocs`
   - one maintainer
   - [x] add an additional maintainer -- @weikang9009 

Any volunteers?

@sjsrey @ljwolf @knaaptime @weikang9009 @slumnitz

**Comment by weikang9009** [comment]
happy to be the maintainer for readthedocs

**Comment by knaaptime** [comment]
i'm game
