### ISSUE TITLE
build error beginning (07/01/2019)

### ISSUE THREAD

**Issue by jGaboardi** [pysal/spaghetti#289]
[Current build errors](https://travis-ci.org/pysal/spaghetti/builds/552926520) apparently stemming from `geopandas`/`conda-forge` on `Python 3.7`. This same error also seems to be affecting [`meta pysal`](https://travis-ci.org/pysal/pysal/builds/553135300), [`libpysal`](https://travis-ci.org/pysal/libpysal/builds/553043405), and [`segregation`](https://travis-ci.org/pysal/segregation/builds/553049888).

@renanxcortes @knaaptime @weikang9009

**Comment by sjsrey** [comment]
Not sure what exactly the issue is, but I think it is related to the travis specification as I tried a number of local installs  using conda environemnts w/wo pip and python3.7 and geopandas and can't reproduce the error. In other words, I can build these environments locally just fine.

**Comment by knaaptime** [comment]
ran into this last week in the sprint with esau. I think it has do do with some dependency conflicts that arise from `channel_priority=strict`. i.e. i think there are some packages that have yet to be released for 3.7 on conda-forge, and since channel priority is strict, conda refuses to get the appropriate versions from defaults

**Comment by weikang9009** [comment]
agree with @knaaptime . removing `channel_priority=strict` sounds promising since the error message points to:
![image](https://user-images.githubusercontent.com/7359284/60530688-2aee1780-9cae-11e9-90f0-464c62fa8411.png)

**Comment by jGaboardi** [comment]
@weikang9009 However, if `channel_priority=strict` is removed then the install of `geopandas`-related dependencies gets funky (unless this has been addressed very recently). I think we should let this one ride for the time being and hope a solution crops up from the `conda-forge` folks. Thoughts? 

@ocefpaf

**Comment by knaaptime** [comment]
that was my inclination

**Comment by ocefpaf** [comment]
> @weikang9009 However, if `channel_priority=strict` is removed then the install of `geopandas`-related dependencies gets funky (unless this has been addressed very recently). I think we should let this one ride for the time being and hope a solution crops up from the `conda-forge` folks. Thoughts?

conda-forge always recommend using `strict` when adding a third party channel. If you remove it things may work but there is no guarantee that the packages are compatible with each other (compilers, dependency version, etc). I'll look into the original issue to see what may be going on there.

**Comment by ocefpaf** [comment]
Filed an issue at https://github.com/conda/conda/issues/8858

Note that when `conda-forge` finished the `readline` migration this CI will be working again but the bug in conda still exists.

**Comment by knaaptime** [comment]
thanks for your help @ocefpaf!

**Comment by ocefpaf** [comment]
BTW, I'm trying to work on the `readline` migration in `conda-forge` and hopefully this will be fixed by tomorrow.

**Comment by ocefpaf** [comment]
Looks like all the packages needed for this project were migrated to the new readline. When you restart the CIs let me know how it goes.

**Comment by jGaboardi** [comment]
@ocefpaf my personal branch of `spaghetti` is now passing and the main `pysal/pysal` is also passing. Other submodules using `geopandas` are currently running, but it looks like we are all good to go. Thanks again for the support!

**Comment by jGaboardi** [comment]
All looks in order.
