### ISSUE TITLE
trailing comma not allowed with surrounding parenthesis

### ISSUE THREAD

**Issue by ljwolf** [pysal/spaghetti#29]
line 2 of `api.py` has a trailing comma.

**Comment by ljwolf** [comment]
this is a python3 error, but it's not too urgent I think. We need it fixed for the release candidate, however.

**Comment by jGaboardi** [comment]
@ljwolf this was fixed in [commit `fe3b4f7`](https://github.com/pysal/spaghetti/pull/25/commits/fe3b4f70937bd0eb1469587acdf81020cad566fc), but has not been merged yet.
