### ISSUE TITLE
Change Read the Docs to GitHub?

### ISSUE THREAD

**Issue by jGaboardi** [pysal/spaghetti#301]
I received the email attached below yesterday from the Read the Docs team. Basically, it says that all RTD hosted sites will have advertisements soon. While this is in no way a knock on their model, maybe it is time to switch over to the GitHub hosted docs, as mentioned in the [August 2019 dev meeting](https://hackmd.io/Kp6Mr5HlTieLikgkzXlgyg?both) and implemented in [PySAL-meta](https://github.com/pysal/pysal/pull/1134). 

Thoughts, @weikang9009 @sjsrey?

>As you might already know, Read the Docs has been using advertising to help build a sustainable business around open source documentation hosting. We call it Ethical Advertising, because we don't allow any third-party scripts for tracking, and all the ads are served from our servers. Since we started, these ads have only been displayed on docs with the Read the Docs or Alabaster themes. We are now changing this, and starting to display ads on all documentation themes. 
>
>You're getting this email because you maintain a project that uses a custom theme, and will soon start getting ads on it. We wanted to be proactive about this change, and alert you. Our blog post has more details on these changes, including how you might opt out: https://urldefense.com/v3/__https://blog.readthedocs.com/fixed-footer-ad-all-themes/__;!5Xm4_O-4tfk!n-8e9c86LvcMedZ_BypZxnjpFDEX_OY_6S4rcJVbS0eEXPjheUB2iFu3Ak76DWjB$ 
>
>Read the Docs is provided for free to all open source projects. Running this service requires multiple people to wear pagers, respond to GitHub issues, and other work that is mostly invisible and thankless. We are using the money generated to help support our community and make the service sustainable.
>
>You can read more about our advertising here: https://urldefense.com/v3/__https://docs.readthedocs.io/page/ethical-advertising.html__;!5Xm4_O-4tfk!n-8e9c86LvcMedZ_BypZxnjpFDEX_OY_6S4rcJVbS0eEXPjheUB2iFu3AqIOCOed$ . We are doing our best to respect our users, while making our service sustainable, and we care that you believe and support the work that we do. Please let us know if you have any questions or concerns, and we will do our best to address them.
>
>If you would like to completely remove advertising from your open source project, but Read the Docs for Business (https://urldefense.com/v3/__https://readthedocs.com__;!5Xm4_O-4tfk!n-8e9c86LvcMedZ_BypZxnjpFDEX_OY_6S4rcJVbS0eEXPjheUB2iFu3Aqi-XAH5$ ) doesn't seem like the right fit, please respond to this email to discuss alternatives to advertising such as our Gold Membership program: https://urldefense.com/v3/__https://readthedocs.org/accounts/gold/subscription/__;!5Xm4_O-4tfk!n-8e9c86LvcMedZ_BypZxnjpFDEX_OY_6S4rcJVbS0eEXPjheUB2iFu3AisyAWni$ .
>
>Cheers, 
>The Read the Docs Team

**Comment by sjsrey** [comment]
I agree - they need to be sustainable so I don't have any issue with their business model. The reason I moved the meta docs off of rtd was the challenges we continually face with getting builds, that work locally, to work remotely.

**Comment by jGaboardi** [comment]
I tried to go through the [PySAL doc PR](https://github.com/pysal/pysal/pull/1134) for how to change up `spaghetti`'s but there were too many files changed to figure out what exactly was happening differently. Is there a specific template you worked from?

**Comment by sjsrey** [comment]
Steps:

1. rename `doc` to `docsrc`
2. add `docs/.nojekyll`
3. in `docsrc` build docs as usual
4. update makefile to copy `docsrc/_build/html/*` into `docs`
5. update repo settings as seen in the figure.

![2019-07-31-2005-1564628705-sel](https://user-images.githubusercontent.com/118042/62560552-262efd00-b832-11e9-9e32-f44857774abd.png)

**Comment by weikang9009** [comment]
Would be nice to move the instructions to http://pysal.org/getting_started where instructions for hosting docs on readthedocs are given.

<img width="1303" alt="image" src="https://user-images.githubusercontent.com/7359284/62561788-c0904000-b834-11e9-8923-06fe90cd127d.png">

**Comment by jGaboardi** [comment]
Maybe we should have both sets of instructions (RTD & GH) just in case others want to keep using RTD?

**Comment by weikang9009** [comment]
> Maybe we should have both sets of instructions (RTD & GH) just in case others want to keep using RTD or are we now actively encouraging GH docs over RTD?

I agree!

**Comment by jGaboardi** [comment]
Should there be PRs for this in both the [submodule_template](https://github.com/pysal/submodule_template) and [pysal.github.io](https://github.com/pysal/pysal.github.io)?

**Comment by jGaboardi** [comment]
Resolved via #303 & #304
