### ISSUE TITLE
get_versions() function

### ISSUE THREAD

**Issue by jGaboardi** [pysal/spaghetti#302]
Add a `get_versions()` function similar to that in `geopandas`.

[`geopandas._version.py`](https://github.com/geopandas/geopandas/blob/master/geopandas/_version.py)

**Comment by jGaboardi** [comment]
This is done via [`versioneer`](https://github.com/warner/python-versioneer).

**Comment by sjsrey** [comment]
Do you have an idea for how this would work with the submodule [contract](https://github.com/pysal/submodule_template/blob/master/PACKAGE_NAME/__init__.py)?

**Comment by jGaboardi** [comment]
No, it was just an idea I had in passing that I thought may be beneficial for us to have here — and in the wider `pysal` ecosystem — for diagnosing errors due to dependency issues. That being said, I am not sure now difficult it would be to implement.

Do you have some specific idea or would doing this violate the submodule contract?

**Comment by sjsrey** [comment]
Right now, anything that works across the packages and needs to query the version numbers is based on the assumption that all packages have the version defined in the first line of the __init__.py file.  Not sure if going with versioneer would require a change in that, or if it could work alongside that but bring additional benefits?

**Comment by jGaboardi** [comment]
I guess my idea was simply having an embedded function for printing out dependency versions and where they were coming from (`pip` vs. `conda`). After another look, `versioneer` does much more than that, which is not something to consider at the moment. Will close this issue for now.
