### ISSUE TITLE
Review docs for links, etc.

### ISSUE THREAD

**Issue by jGaboardi** [pysal/spaghetti#338]
Following #336 & #337, a review of the docs are needed for stale/broken links. Examples include:
  *  [`libpysal.weights.weights.W`](https://libpysal.readthedocs.io/en/latest/generated/libpysal.weights.W.html#libpysal.weights.W) in [`spaghetti.Network.extract_components`](https://pysal.org/spaghetti/generated/spaghetti.Network.extract_components.html#spaghetti.Network.extract_components)

Specifically check for links to other packages link `geopandas`. Be sure to check check the generated locally for format and link functionality.

**Comment by rahul799** [comment]
@jGaboardi I would like to work on this. I am new to Scrapy, and not sure if it is necessary to be assigned the issue to work on it? Can you assign this to me?

**Comment by jGaboardi** [comment]
@rahul799 Thanks for reaching out! It is not necessary to be assigned and contributions are welcome! If you haven't reviewed to our [Community Guidelines](http://pysal.org/community), [Contributing Guidelines](https://github.com/pysal/pysal/wiki#pysal-development-wiki), and [Getting Started w/PySAL](http://pysal.org/getting_started), please do so and let me know if you have any questions.

**Comment by jGaboardi** [comment]
* ensure external package/class/function references are in the proper format for [`intersphinx_mapping`](https://github.com/pysal/spaghetti/blob/d4930d62c9073791b9f08dac6f4ee698808050e2/docsrc/conf.py#L254-L262)

**Comment by rahul799** [comment]
@jGaboardi Thanks for the response. I have read all the Guidelines & am ready to contribute. I just wanted to know what exactly I need to do with the broken links. As in, do I need to remove them or commenting them out will be fine?

**Comment by jGaboardi** [comment]
>  just wanted to know what exactly I need to do with the broken links. As in, do I need to remove them or commenting them out will be fine?

@rahul799 I would like to incorporate [intersphinx mapping](https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html) into the `spaghetti` docs (see comment [above](https://github.com/pysal/spaghetti/issues/338#issuecomment-564583144)). This is something that I have never tried (it is completely new to me), and was brought up in the [`libpysal`](https://github.com/pysal/libpysal/pull/209#issuecomment-561977051) repo by @knaaptime (original PR [here](https://github.com/ryan-roemer/sphinx-bootstrap-theme/pull/193)). Also, see the pysal/submodule_template#23 PR by @weikang9009.

**Comment by knaaptime** [comment]
I think the reference to `libpysal.weights.weights.W` should actually be `libpysal.weights.W` (which would properly point [here](https://pysal.org/libpysal/generated/libpysal.weights.W.html#libpysal.weights.W) as long as intersphinx is set to point at https://pysal.org/libpysal/ instead of http://readthedocs.libpysal.io/ where the docs are no longer being published

**Comment by knaaptime** [comment]
>As in, do I need to remove them or commenting them out will be fine?

neither, actually. They need to be edited to ensure that they properly reference the function or class they point to. Typically, that just means using the full module path to the function. So if you wanted to reference Pysal's [open function](https://pysal.org/libpysal/generated/libpysal.io.open.html#libpysal.io.open), you would use `libpysal.io.open`

**Comment by jGaboardi** [comment]
@rahul799, @knaaptime provides an excellent example of what we want to do here: have `sphinx` be able to automatically generate links to other published doc sites. In order for this to happen, all references to external objects must be in the correct format and the package must be contained within the [`intersphinx_mapping`](https://github.com/pysal/spaghetti/blob/d4930d62c9073791b9f08dac6f4ee698808050e2/docsrc/conf.py#L254-L262) variable found in [`docsrc/conf.py `](https://github.com/pysal/spaghetti/blob/d4930d62c9073791b9f08dac6f4ee698808050e2/docsrc/conf.py).

**Comment by rahul799** [comment]
@jGaboardi , @knaaptime I have understood the task. Will work accordingly. Thanks for the help.

**Comment by jGaboardi** [comment]
#339

**Comment by rahul799** [comment]
@jGaboardi , @knaaptime .Please have a look at this [PR](https://github.com/pysal/spaghetti/pull/339).  I have never worked with `sphinx` & I am new to open source community & this is my first contribution so let me know if any changes I need to make.

**Comment by jGaboardi** [comment]
This is being address in #342
