### ISSUE TITLE
populating sphinx docs

### ISSUE THREAD

**Issue by jGaboardi** [pysal/spaghetti#37]
@weikang9009 would you be able to provide assistance to getting the `sphinx` docs built for `spaghetti`? I have gotten as far as doing an initial build on [`readthedocs`](https://pysalspaghetti.readthedocs.io/en/latest/#), but I am not sure on how to proceed.

**Comment by weikang9009** [comment]
Sure. We can talk about it at the dev meeting this Friday and decide how to proceed.

**Comment by jGaboardi** [comment]
resolve in #98
