### ISSUE TITLE
Binder is broken for network-analysis

### ISSUE THREAD

**Issue by sjsrey** [pysal/spaghetti#399]
On the [Spatial network analysis](https://pysal.org/spaghetti/notebooks/network-analysis.html) example in the tutorial, the [notebook](https://mybinder.org/v2/gh/pysal/spaghetti/master?filepath=docsrc/notebooks/network-analysis.ipynb) in the binder crashes with:

![2020-01-25-1513-1579994026-sel](https://user-images.githubusercontent.com/118042/73128510-4f307f00-3f85-11ea-8862-b8a5b110e89f.png)

**Comment by jGaboardi** [comment]
I am on the edge on doing a release, hopefully done tonight. The issue seems to be that the environment is fluid at the moment. This may lead to a larger question of tagged releases vs. pure code freezes. If I understand correctly, the PySAL meta releases are tied to release tags, but the `binder` builds are tied to the current master.

**Comment by sjsrey** [comment]
I'm rewriting the PySAL meta release docs so the api pages points back to the subpackage api page [see here](https://github.com/sjsrey/pysal/blob/docs/docsrc/api.rst). 

I reported this bug as  was following the links in the new meta scheme and came across the links so I thought I'd report them.

**Comment by jGaboardi** [comment]
The [`binder`](https://notebooks.gesis.org/binder/jupyter/user/pysal-spaghetti-8m3f2gol/notebooks/docsrc/notebooks/network-analysis.ipynb) renders now.

**Comment by jGaboardi** [comment]
Thanks for the heads up!

**Comment by sjsrey** [comment]
When I refresh I'm still getting:

![2020-01-25-1533-1579995215-sel](https://user-images.githubusercontent.com/118042/73128710-49886880-3f88-11ea-93e0-d68913ab5b85.png)

**Comment by jGaboardi** [comment]
hmmm. I am able to run the notebook with issue on FireFox. Just did again right now.

https://notebooks.gesis.org/binder/jupyter/user/pysal-spaghetti-8m3f2gol/notebooks/docsrc/notebooks/network-analysis.ipynb

**Comment by jGaboardi** [comment]
But binders almost never seem to run when I am using Safari.

**Comment by sjsrey** [comment]
That link gets me:

![2020-01-25-1537-1579995453-sel](https://user-images.githubusercontent.com/118042/73128734-a552f180-3f88-11ea-90d3-9ddad6fa7f40.png)

**Comment by sjsrey** [comment]
The link on the tutorial page: https://pysal.org/spaghetti/notebooks/network-analysis.html
to the binder is the one that throws the error on step 41.

**Comment by jGaboardi** [comment]
I can open that link without issue on FireFox, but not Safari.

**Comment by jGaboardi** [comment]
Which browser are you using?

**Comment by sjsrey** [comment]
firefox

**Comment by sjsrey** [comment]
https://mybinder.org/v2/gh/pysal/spaghetti/master?filepath=docsrc/notebooks/network-analysis.ipynb

The link is different from: https://notebooks.gesis.org/binder/jupyter/user/pysal-spaghetti-8m3f2gol/notebooks/docsrc/notebooks/network-analysis.ipynb

**Comment by jGaboardi** [comment]
huh... don't where I got that either... Is the tutorial binder working for you now? I just opened and ran it again.

**Comment by sjsrey** [comment]
Its working in chrome on linux. Will try on firefox again.

**Comment by sjsrey** [comment]
On firefox I get the error on step 41/51. Weird.

**Comment by jGaboardi** [comment]
This seems to be the link we click on to get to the build page:
>https://mybinder.org/v2/gh/pysal/spaghetti/master?filepath=docsrc/notebooks/network-analysis.ipynb

And this one is this built image:
>https://notebooks.gesis.org/binder/jupyter/user/pysal-spaghetti-8m3f2gol/notebooks/docsrc/notebooks/network-analysis.ipynb

Just so you know I'm not lying about it:

<img width="1280" alt="Screenshot 2020-01-25 18 50 06" src="https://user-images.githubusercontent.com/8590583/73128834-8ca40500-3fa3-11ea-8f2d-f9fe21e776bd.png">

**Comment by sjsrey** [comment]
Well, at least this might give someone a clue if they hit the error I'm hitting using firefox on linux. We can close as it works on chrome on linux .
