### ISSUE TITLE
Some tutorial links giving 404

### ISSUE THREAD

**Issue by sjsrey** [pysal/spaghetti#400]
The [second](https://pysal.org/spaghetti/notebooks/connected-components.html) and [third](https://pysal.org/spaghetti/notebooks/shortest-path-visualization.html) links are dead.

**Comment by jGaboardi** [comment]
see [here](https://github.com/pysal/spaghetti/issues/399#issuecomment-578452563)

**Comment by jGaboardi** [comment]
The links are fixed in #398
