### ISSUE TITLE
Appveyor still being triggered

### ISSUE THREAD

**Issue by jGaboardi** [pysal/spaghetti#454]
Appveyor is [still being triggered](https://ci.appveyor.com/project/SergeRey/spaghetti/builds/31727195) from spaghetti despite removal of the webhook, etc. So it seems like something may have to be done from the `SergeRey/spaghetti` appveyor account to disable the triggered build (which automatically fail in `pysal/spaghetti`because there is no longer an `appveyor.yml` file).

**Comment by jGaboardi** [comment]
@sjsrey when you have a minute can you handle this?

**Comment by sjsrey** [comment]
I disabled av on sjsrey/spaghetti. Let me know if this fixes it.

**Comment by jGaboardi** [comment]
Resolved.
