### ISSUE TITLE
Network L Function

### ISSUE THREAD

**Issue by jGaboardi** [pysal/spaghetti#467]
Add the Network *L* function from O’Sullivan and Unwin (2010) as a supplement for removing the *G* and *F* functions.

* **D. O’Sullivan and D. J. Unwin**. *Point Pattern Analysis*, chapter 5, pages 121–156. John Wiley & Sons, Ltd, 2010. doi:10.1002/9780470549094.ch5.

**Comment by jGaboardi** [comment]
The planar *L* function uses <img src="https://render.githubusercontent.com/render/math?math=\pi"> due to it's reliance on circular buffers to detect point, as seen in equation 5.14, page 147 (see also equation 5.13):
<img src="https://render.githubusercontent.com/render/math?math=L(d)=\sqrt{\frac{K(d)}{\pi}}-d" height="50" width="500">

Question:
 * What would be (is there) an alternative metric in network space to use for standardization?

Thoughts, @sjsrey, @ljwolf ?

**Comment by sjsrey** [comment]
I don't think there is an analogue for the network case. Looking through the Okabe book, I don't see that they use the L(d) function, but keep the unstandardized K(d) function. Maybe we should do the same?

**Comment by jGaboardi** [comment]
@sjsrey, That was my initial thought. Thanks for the quick feedback.

**Comment by jGaboardi** [comment]
Closing for now as infeasible/irrelevant.
