### ISSUE TITLE
Wrong distance units in split_arcs description

### ISSUE THREAD

**Issue by anitagraser** [pysal/spaghetti#525]
One of the following two has to be wrong:

https://pysal.org/spaghetti/notebooks/network-spatial-autocorrelation.html

> Moran’s I on a network split into **200-meter segments**
> ```
> n200 = ntw.split_arcs(200.0)
> ```

https://pysal.org/spaghetti/generated/spaghetti.Network.html#spaghetti.Network.split_arcs

> Split the network into a segments of **200 distance units in length** (US feet in this case.). 
> ```
> n200 = ntw.split_arcs(200.0)
> ```

As far as I can see, both refer to the same streets.shp with .prj

```
PROJCS["NAD_1983_StatePlane_Arizona_Central_FIPS_0202_Feet",GEOGCS["GCS_North_American_1983",DATUM["D_North_American_1983",SPHEROID["GRS_1980",6378137.0,298.257222101]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Transverse_Mercator"],PARAMETER["False_Easting",699998.6],PARAMETER["False_Northing",0.0],PARAMETER["Central_Meridian",-111.9166666666667],PARAMETER["Scale_Factor",0.9999],PARAMETER["Latitude_Of_Origin",31.0],UNIT["Foot_US",0.3048006096012192]]
```

**Comment by jGaboardi** [comment]
This seems to be a typo of mine in [network-spatial-autocorrelation](https://pysal.org/spaghetti/notebooks/network-spatial-autocorrelation.html) notebook. You are correct that it should be 200-foot segments, etc.

**Comment by jGaboardi** [comment]
It turns out there were several more (GIS) bugs and typos in some of the other notebooks that I found thanks to you bringing this up. I should be able to dig more into #526 and #527 over the weekend. Thanks again for finding this and raising the issue!
