### ISSUE TITLE
Strange count_per_link() results for networks generated using ntw.split_arcs() 

### ISSUE THREAD

**Issue by anitagraser** [pysal/spaghetti#526]
The counts per link are all over the place when I use a split network. I've created a notebook to illustrate the issue: 

https://github.com/anitagraser/spaghetti/blob/af4cc443be47c2e0b678b6b4a0deaf970d026207/notebooks/debug-counts-on-split-arcs.ipynb

![image](https://user-images.githubusercontent.com/590385/95112933-e7e8e280-0741-11eb-8298-9608142ac6c3.png)

**Comment by jGaboardi** [comment]
Related to #527. Resolve this first before proceeding to that issue.

**Comment by jGaboardi** [comment]
See the original comment [here](https://gitter.im/pysal/pysal?at=5f7b479bed7be16b3cbbd2c4).

**Comment by jGaboardi** [comment]
This is being fixed in #535. Once I merge that in I plan to follow up with some extra segmentation examples in the [network segmentation](https://pysal.org/spaghetti/notebooks/network-segmentation.html) notebook.
