### ISSUE TITLE
DRY version documentation

### ISSUE THREAD

**Issue by jGaboardi** [pysal/spaghetti#53]
mimic [giddy](https://github.com/pysal/giddy) for declaring submodule version in one place [`__init__.py`](https://github.com/pysal/giddy/blob/master/giddy/__init__.py)

**Comment by weikang9009** [comment]
[pysal/submodule_template](https://github.com/pysal/submodule_template) is now a better place to look at!

See how to version your package:
* [__ini__.py](https://github.com/pysal/submodule_template/blob/master/PACKAGE_NAME/__init__.py)
* [setup.py](https://github.com/pysal/submodule_template/blob/master/setup.py#L5)

**Comment by jGaboardi** [comment]
@weikang9009 thanks!

**Comment by jGaboardi** [comment]
resolved in PR #60
