### ISSUE TITLE
Is sphinx_gallery needed for docs?

### ISSUE THREAD

**Issue by jGaboardi** [pysal/spaghetti#558]
Is `sphinx_gallery` needed for building the docs? Found in [`requirements_docs.txt`](https://github.com/pysal/spaghetti/blob/d3cbda62ed6cdfd2b6a4fb9bdfcb084610e6031b/requirements_docs.txt#L6), but may be actually not using. See also geopandas/geopandas#1731.

**Comment by weikang9009** [comment]
The current template is not using it. I remember we were considering using it to showcase the application examples, but did not use it in the end. I think you can safely delete it. The submodule_template does not include it as a requirement. https://github.com/pysal/submodule_template/blob/master/requirements_docs.txt

**Comment by jGaboardi** [comment]
#565
