### ISSUE TITLE
[JOSS review] Manuscript statement of need

### ISSUE THREAD

**Issue by martibosch** [pysal/spaghetti#575]
The "Statement of need" section of the manuscript does not actually feature a statement of need but rather a short review of related tools. I believe that a proper statement of need could be added after the first (and only) paragraph of the section. Such a statement should explain which aspects of spaghetti represent an improvement over the reviewed tools as well as who the target audience is. In line with the comment above, the authors might actually consider collapsing this section with the summary (it is just a suggestion, but I understand if the authors prefer having two separate sections - see also #574).

https://github.com/openjournals/joss-reviews/issues/2826

**Comment by jGaboardi** [comment]
Thank you for the good suggestions to improve the manuscript!  We have incorporated information comprising a statement of need in the Related Works & Statement of Need section as suggested. As is also addressed in Issue #580, `spaghetti` is not a new Python package, but evolved from core PySAL functionality to a specialized submodule in the PySAL federation (originally `pysal.network`), which was in development prior to packages such OSMnx and concurrently with NetworkX. Importantly, package integration in the early spatial/scientific Python stack was problematic enough for the PySAL team to decide on “no external dependencies'' policy, which was a main driver in submodules like `pysal.network`. Owing to the co-development of network functionality found within `spaghetti` and the wider PySAL ecosystem, the package provides specialized network functionality that integrates with the rest of the PySAL ecosystem. This allows users of `spaghetti`’s network functionality to access spatial analysis functionality that complements network analysis, such as geovisualization with `splot` or other spatial statistical tools with `esda`.

**Comment by martibosch** [comment]
Hello again @jGaboardi,

in my opinion, the current statement of need should be shortened so that it focuses more on what the target audience can do with spaghetti that cannot be done with other existing tools (e.g., read and analyze network data within the PySAL ecosystem) rather than reviewing the timeline of how PySAL started and how spaghetti became a separate component. This historical perspective could be somewhere in the documentation site, but I believe that the JOSS paper should be as brief as possible and focus on the functionalities and what users can get from the library from a more practical standpoint.

Best,
Martí

**Comment by jGaboardi** [comment]
@martibosch I have trimmed down the Statement of Need section by adding the topic sentence of the second paragraph into the first paragraph and removing the second paragraph altogether.
