### ISSUE TITLE
[JOSS review] Manuscript Figure 1 (PySAL logo)

### ISSUE THREAD

**Issue by martibosch** [pysal/spaghetti#576]
I think that Figure 1 of the manuscript (i.e., the PySAL logo) is not needed and should hence be deleted - especially considering that JOSS papers tend to be very brief.
https://github.com/openjournals/joss-reviews/issues/2826

**Comment by jGaboardi** [comment]
Thank you for bringing this point. We agree with this suggestion. We have removed the image in #588.
