### ISSUE TITLE
[JOSS review] Improve the quickstart notebook

### ISSUE THREAD

**Issue by martibosch** [pysal/spaghetti#578]
In the line of #577, the quickstart notebook could be a bit more thorough in showcasing the main functionalities of spaghetti. For instance, it first shows the user how to instantiate a `spaghetti.Network` object, it could mention other ways of instantiating such an object, e.g., from `libpysal.cg.Chain` as done in the connected components notebook or as a regular lattice as done in the shortest path visualization notebook. This could be done in the form of a markdown cell with a couple of brief sentences and the respective links to the ohter noteooks of the tutorial as well as the corresponding API documentation.
https://github.com/openjournals/joss-reviews/issues/2826

**Comment by jGaboardi** [comment]
Thank you for this valuable suggestion. We have addressed this issue by making the suggested changes in the Quickstart notebook. See also #603.
