### ISSUE TITLE
[JOSS review] Incomplete API documentation site

### ISSUE THREAD

**Issue by martibosch** [pysal/spaghetti#579]
The [API documentation](https://pysal.org/spaghetti/api.html) site is incomplete, e.g., missing `spaghetti.network.Network.snapobservations`, `spaghetti.network.Network.split_arcs` and many other relevant methods (which are in fact well documented in their respective docstrings).

https://github.com/openjournals/joss-reviews/issues/2826

**Comment by jGaboardi** [comment]
@martibosch the API docs for `spaghetti.Network.snapobservations` are [here](https://pysal.org/spaghetti/generated/spaghetti.Network.html#spaghetti.Network.snapobservations) and `spaghetti.network.Network.split_arcs` are [here](https://pysal.org/spaghetti/generated/spaghetti.Network.html#spaghetti.Network.split_arcs). Which were the others that were missing?

**Comment by martibosch** [comment]
my mistake 😓 I did not find them listed in the [API documentation](https://pysal.org/spaghetti/api.html) page but this is because they are actually methods of the Network class (which does appear in the page). Closing 💪🏻

**Comment by jGaboardi** [comment]
> my mistake 😓 I did not find them listed in the [API documentation](https://pysal.org/spaghetti/api.html) page but this is because they are actually methods of the Network class (which does appear in the page). Closing 💪🏻

No problem at all!
