### ISSUE TITLE
Update copyright year

### ISSUE THREAD

**Issue by jGaboardi** [pysal/spaghetti#597]
Update the `copyright` variable in [`conf.py`](https://github.com/pysal/spaghetti/blob/0a1f878f72fdd33eadd66324445511109078fafa/docs/conf.py#L56) to read: `"2018-, pysal developers"`

**Comment by jGaboardi** [comment]
@sjsrey Instead of using a starting copyright year of 2018, should we instead be using 2005 or 2010, as stated in the[ PySAL History](https://pysal.org/about/#history)?

**Comment by sjsrey** [comment]
This would be good to discuss at a future Dev meeting.

**Comment by jGaboardi** [comment]
Added to the agenda for [2021-02-05](https://hackmd.io/wvl8UXaKSeiFq-JCjBNPwA?both#copyright-year-jGaboardi).

**Comment by jGaboardi** [comment]
The [license](https://github.com/pysal/spaghetti/blob/main/LICENSE.txt) states 2017, so updating [`conf.py`](https://github.com/pysal/spaghetti/blob/0a1f878f72fdd33eadd66324445511109078fafa/docs/conf.py#L56) to read: `"2017-, pysal developers"`
