### ISSUE TITLE
Blank LISA plot

### ISSUE THREAD

**Issue by anitagraser** [pysal/spaghetti#656]
**Describe the bug**
Using spaghetti 1.6.4, I only get blank LISA plots.

**To Reproduce**
Run: https://github.com/pysal/spaghetti/blob/main/notebooks/network-spatial-autocorrelation.ipynb

**Screenshots**

![image](https://user-images.githubusercontent.com/590385/144008968-88f12cdc-ad1c-40c4-8221-bf69b2e5ef40.png)

**System & Versions**
![image](https://user-images.githubusercontent.com/590385/144009366-512bc07f-81c4-49aa-88a0-0820e61d6c16.png)

**Comment by martinfleis** [comment]
Hi Anita,

That is a bug in splot we have fixed in https://github.com/pysal/splot/pull/140. You can try pulling the master, the fix has not been released yet (cc @slumnitz).

**Comment by jGaboardi** [comment]
Original issue in pysal/splot#139.

**Comment by jGaboardi** [comment]
@anitagraser a fresh version of `splot` has been released that includes the fix and it is now up on `conda-forge`.
