### ISSUE TITLE
Cut release for meta by 01/10

### ISSUE THREAD

**Issue by jGaboardi** [pysal/spaghetti#658]
Cut `spaghetti` release for meta release. ASAP.

@gegen07 @martinfleis @sjsrey

**Comment by martinfleis** [comment]
Is there any blocker?

**Comment by jGaboardi** [comment]
nope! this is simply a reminder.

**Comment by jGaboardi** [comment]
done -- https://github.com/pysal/spaghetti/releases/tag/v1.6.5
