### ISSUE TITLE
Stalling CI tests

### ISSUE THREAD

**Issue by jGaboardi** [pysal/spaghetti#666]
I'm not sure what the actual problem is, and it doesn't seem like we can do anything about it, but for the past week or so the [CI matrix stalls out](https://github.com/pysal/spaghetti/actions/runs/1821081489) in one or more builds, seemingly at random in regards to OS. Probably we'll have to simply wait it out, but I wanted to make a record of it.

**Comment by martinfleis** [comment]
It is random in regards to OS but not in regards to the test. It seems to always hang at `test_squared_distance_point_link`. Maybe some conflict between pytest's multiprocessing and numpty's multiprocessing in `dot`?

**Comment by jGaboardi** [comment]
Good find! I'll try to look into it.

**Comment by jGaboardi** [comment]
maybe a similar problem happening in [`segregation`](https://github.com/pysal/segregation/pull/192), but on Windows and without `pytest-xdist`.
