### ISSUE TITLE
Update biblioteca numpy

### ISSUE THREAD

**Issue by Nilsonfsilva** [pysal/spaghetti#705]
Hey!
I'm a member of the debian project in the area of ​​software packaging.

Months ago I decided to pack and keep the spaghetti in our distribution.

Recently numpy library made some updates, as a result some packages are breaking.

Here are some fixes.
Without them, spaghetti cannot be built:
```
Index: spaghetti/spaghetti/util.py
===================================================================
--- spaghetti.orig/spaghetti/util.py
+++ spaghetti/spaghetti/util.py
@@ -244,7 +244,7 @@ def dijkstra(ntw, v0, initial_dist=numpy
                 unvisited.add(v1)
 
     # cast preceding vertices list as an array of integers
-    pred = numpy.array(pred, dtype=numpy.int)
+    pred = numpy.array(pred, dtype=int)
      return distance, pred
```
Hope this helps!
Nilson Silva

**Comment by jGaboardi** [comment]
@Nilsonfsilva, thanks for the report! Which version of `spaghetti` are yo

Is the problem with the [current implementation](https://github.com/pysal/spaghetti/blob/7fdae0c1861281b5b7730fc4073fb8673a09047c/spaghetti/util.py#L246) (`pred = numpy.array(pred, dtype=int)`) or with `pred = numpy.array(pred, dtype=numpy.int)`? Because [`numpy.int` is deprecated](https://numpy.org/devdocs/release/1.20.0-notes.html#using-the-aliases-of-builtin-types-like-np-int-is-deprecated). 


```python
Python 3.11.0 | packaged by conda-forge | (main, Jan 15 2023, 05:44:48) [Clang 14.0.6 ]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.8.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import numpy

In [2]: numpy.__version__
Out[2]: '1.24.1'

In [3]: numpy.int
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[3], line 1
----> 1 numpy.int

File ~/miniconda3/envs/py311_spaghetti/lib/python3.11/site-packages/numpy/__init__.py:284, in __getattr__(attr)
    281     from .testing import Tester
    282     return Tester
--> 284 raise AttributeError("module {!r} has no attribute "
    285                      "{!r}".format(__name__, attr))

AttributeError: module 'numpy' has no attribute 'int'

In [4]: numpy.int32, numpy.int64
Out[4]: (numpy.int32, numpy.int64)
```

**Comment by jGaboardi** [comment]
Also, can you provide a link to your CI with the failed build?

**Comment by martinfleis** [comment]
I think that the proposed fix is already implemented and @Nilsonfsilva is not running the latest version. @Nilsonfsilva can you post the version of spaghetti you are working with?

**Comment by Nilsonfsilva** [comment]
Hello
I already updated!
Thanks!



Nilson F. Silva

________________________________
De: Martin Fleischmann ***@***.***>
Enviado: quarta-feira, 18 de janeiro de 2023 05:40
Para: pysal/spaghetti ***@***.***>
Cc: Nilsonfsilva ***@***.***>; Mention ***@***.***>
Assunto: Re: [pysal/spaghetti] Update biblioteca numpy (Issue #705)


I think that the proposed fix is already implemented and @Nilsonfsilva<https://github.com/Nilsonfsilva> is not running the latest version. @Nilsonfsilva<https://github.com/Nilsonfsilva> can you post the version of spaghetti you are working with?

**Comment by martinfleis** [comment]
Great. Let us know if any other issues come up.
