### ISSUE TITLE
[ENH] streets/network and points need to be in the same CRS/EPSG

### ISSUE THREAD

**Issue by jGaboardi** [pysal/spaghetti#71]
@sjsrey @ljwolf 

Currently, there is no way to enforce that the line data and point data are in the same coordinate reference system. When they are in wildly different projections an uninformative `AssertionError` with no message is thrown from `libpysal.cg.rtree` (meaning there are no points within a `Rect` object when building the lookup tree).  Furthermore, if the lines and points are in similar CRSs there might be no error, but the results would be invalid as the spatial relationship / locations between the lines and points would  not be preserved. Enforcing, or at minimum checking for, the same crs is a simple one-liner when the input data is a `geopandas.GeoDataFrame`, but do we have a method for this baked in when the input is `pysal.io`/`libpysal.io` ?

**Comment by sjsrey** [comment]
I think the crs handling should be done outside of pysal/libpysal.

**Comment by jGaboardi** [comment]
In [`util.py`](https://github.com/pysal/spaghetti/blob/e945b16820234547b0d65e3c03d9eb3cb9e4f061/spaghetti/util.py#L342) (the operation may actually be happening in [this line](https://github.com/pysal/spaghetti/blob/e945b16820234547b0d65e3c03d9eb3cb9e4f061/spaghetti/util.py#L351)) maybe add:

```python
try:
    r = cg.Rect(x0, y0, x1, y1)
except AssertionError as e:
    raise e('There are no point within `cg.Rect`. Check data coordinate reference systems.')
```

This would at minimum throw an informative error while not strictly enforcing any actual `crs` checking or transformations.

**Comment by jGaboardi** [comment]
Closing this issue for as not able to consistently reproduce or come up with a universal/efficient solution.
