### ISSUE TITLE
Can we run network kernel density estimation using spaghetti?

### ISSUE THREAD

**Issue by bright1993ff66** [pysal/spaghetti#711]
**Is your feature request related to a problem? Please describe.**
I am working on one network kernel density estimation problem. The task is to estimate the road network density of motor vehicle collision records in New York.

**Describe the solution you'd like**
A convenient tool that can generate the network kernel density based on point features (such as collision records), network shapefile (e.g., road network), and the city border (a polygon)

**Describe alternatives you've considered**
I am using the network kernel density estimation tool in the R package [spNetwork](https://jeremygelb.github.io/spNetwork/articles/NKDE.html) to complete this task. But a python class that can complete this task is preferable for Python users.

**Additional context**
Some reference:
1. [Kernel Density Estimation of traffic accidents in a network space](https://www.sciencedirect.com/science/article/pii/S0198971508000318)
2. [Applying Network Kernel Density Estimation (NKDE) and Temporal Network Kernel Estimation (TNKDE) for Generating Safer Routes](https://cusg.ornl.gov/workshops/IWCTS2022/proceeding/papers/paper5.pdf)

**Comment by jGaboardi** [comment]
Thanks for opening this @bright1993ff66. This is not currently possible within `spaghetti`. I seem to remember that @knaaptime was working with network KDE but I can't remember the package it was with.

PRs are always welcome!

**Comment by jGaboardi** [comment]
Also, the modernization and update of `spaghetti` has been on my To Do list for some years now. Along with the Network KDE idea. Seeing as how I have had no bandwidth for implementing any of those ideas in the past 5 years, I highly doubt I will in the near or mid term future.

* **xref**:
  * https://github.com/pysal/spaghetti/discussions/195
  * https://github.com/pysal/spaghetti/discussions/258
  * https://github.com/pysal/spaghetti/issues/118
  * https://github.com/pysal/spaghetti/discussions/403

**Comment by bright1993ff66** [comment]
Dear @jGaboardi and @knaaptime ,

Thank you for your help and suggestions about this topic! I will try the tools suggested by @knaaptime and see if I can work this out 🛩️
