### ISSUE TITLE
Memory leak in `full_distance_matrix` when `n_processes > 1`

### ISSUE THREAD

**Issue by iboates** [pysal/spaghetti#715]
**Describe the bug**
The multiprocessing implementation in `full_distance_matrix` opens a multiprocessing pool but then never closes it. [(Relevant line)](https://github.com/pysal/spaghetti/blob/main/spaghetti/network.py#L1629)

Python will not automatically release the memory from these subprocesses. They have to be explicitly closed, otherwise the memory hangs around and accumulates until the process gets killed out of desperation by the OS. Indeed it is hard to notice if you are just running the function as a one-off, since the main thread will finish successfully and it's not an issue. But if you then run the function in a loop, then the RAM gets very sad.

I had this problem on a project I was working on a few months ago and I believe that the code here makes this exact same mistake.

It should be fixable two ways (with the first being more "pythonic").

Either use the "context manager interface", which should close the connection properly as soon as it goes out of scope:

```
            with mp.Pool(processes=cores) as p:

                # calculate the shortest path and preceding
                # vertices for traversal route by mapping each process
                distance_pred = p.map(util.dijkstra_mp, zip(repeat(self), self.vertex_list))

                # set range of iterations
                iterations = range(len(distance_pred))

                # fill shortest paths
                distance = [distance_pred[itr][0] for itr in iterations]

                # fill preceding vertices
                pred = numpy.array([distance_pred[itr][1] for itr in iterations])

                # iterate of network vertices and generate
                # the shortest path tree for each
                for vtx in self.vertex_list:
                    if gen_tree:
                        tree = util.generatetree(pred[vtx])
                    else:
                        tree = None

                    # populate distances and paths
                    self.distance_matrix[vtx] = distance[vtx]
                    self.network_trees[vtx] = tree
```

Or close it explicitly after it's done:

```
            p = mp.Pool(processes=cores)

            # calculate the shortest path and preceding
            # vertices for traversal route by mapping each process
            distance_pred = p.map(util.dijkstra_mp, zip(repeat(self), self.vertex_list))

            # set range of iterations
            iterations = range(len(distance_pred))

            # fill shortest paths
            distance = [distance_pred[itr][0] for itr in iterations]

            # fill preceding vertices
            pred = numpy.array([distance_pred[itr][1] for itr in iterations])

            # iterate of network vertices and generate
            # the shortest path tree for each
            for vtx in self.vertex_list:
                if gen_tree:
                    tree = util.generatetree(pred[vtx])
                else:
                    tree = None

                # populate distances and paths
                self.distance_matrix[vtx] = distance[vtx]
                self.network_trees[vtx] = tree```

            p.close()
```

I prefer the first option and I can submit a PR if you agree. Maybe there are also other instances of this happening elsewhere in the code?

**To Reproduce**
Run `ntw.allneighbordistances` in a loop with `n_processes > 1`, preferably with a fairly large network to see the catastrophic memory accumulation hoarding

**Expected behavior**
The multiprocessing pool should be closed to release its memory

**Screenshots**

**Additional context**

**System & Versions**
- Platform information:
```python
>>> import os; print(os.name, os.sys.platform);print(os.uname())
```
- Python version: 3.8.10 (default, Mar 13 2023, 10:26:41) [GCC 9.4.0]

- spaghetti version: 1.7.2

- libpysal version: 4.7.0

- SciPy version: 1.10.1

- NumPy version:1.24.2

- GeoPandas verion (if applicable): 0.12.2

**Comment by jGaboardi** [comment]
Hi, @iboates. Thanks for the report! I think the first option sounds good and would welcome a PR for review.

**Comment by iboates** [comment]
Sorry @jGaboardi looks like I never got around to doing this, thanks for fixing it though
