### ISSUE TITLE
Error in using spaghetti.element_as_gdf

### ISSUE THREAD

**Issue by adhamenaya** [pysal/spaghetti#742]
**Describe the bug**
Error while using **_spaghetti.element_as_gdf_**

**To Reproduce**
```
Run the following code that was tasked from the library tutorial:
%config InlineBackend.figure_format = "retina"
%load_ext watermark
%watermark

import esda
import libpysal
import matplotlib
import matplotlib_scalebar
from matplotlib_scalebar.scalebar import ScaleBar
import numpy
import spaghetti
import splot

%matplotlib inline
%watermark -w
%watermark -iv

ntw = spaghetti.Network(in_data=libpysal.examples.get_path("streets.shp"))
ntw

_, arc_df = spaghetti.element_as_gdf(ntw, vertices=True, arcs=True)
arc_df.head()
```

**System & Versions**
- Platform information:
posix darwin
posix.uname_result(sysname='Darwin', nodename='eduroam-int-dhcp-97-26-155.ucl.ac.uk', release='22.2.0', version='Darwin Kernel Version 22.2.0: Fri Nov 11 02:04:44 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T8103', machine='x86_64')

- Python version: 
3.10.9 (main, Mar  1 2023, 12:33:47) [Clang 14.0.6 ]

- spaghetti version:
1.6.8

- libpysal version:
4.6.2

- SciPy version:
1.10.0

- NumPy version:
1.23.5

- GeoPandas version (if applicable):
0.13.0

- More info:
I received the following error in the this line of code:
`_, arc_df = spaghetti.element_as_gdf(ntw, vertices=True, arcs=True)
`

```
AttributeError: You are calling a geospatial method on the GeoDataFrame, but the active geometry column to use has not been set. 
There are no existing columns with geometry data type. You can add a geometry column as the active geometry column with df.set_geometry.
```

**Comment by jGaboardi** [comment]
Thanks for the report!

This error has been fixed in the [latest release of `spaghetti`](https://github.com/pysal/spaghetti/releases/tag/v1.7.4). Please upgrade to `spaghetti==1.7.4`.

xref: https://github.com/pysal/spaghetti/issues/717, https://github.com/pysal/spaghetti/issues/718

**Comment by adhamenaya** [comment]
@jGaboardi yeah!! thank you soo much!!!
