### ISSUE TITLE
312-dev CI failures [2024-03-16]

### ISSUE THREAD

**Issue by jGaboardi** [pysal/spaghetti#762]
Current [failures in 312-dev CI](https://github.com/pysal/spaghetti/actions/runs/8303951431/job/22728921311#step:6:194) are due to a `fiona`/`geopandas` compatibility issue that is being resolved in https://github.com/geopandas/geopandas/pull/3209. @martinfleis My thought is to simply ignore here for now unless you think there is a reason to pin `fiona<=1.9.x`?

**Comment by martinfleis** [comment]
Ignore. It will be resolved in upstream.
